name: null
dependencies:
  - descartes
  - folium
  - geopandas
  - ipywidgets
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib
  - pandas
  - pip:
    - cufflinks
  - ployly
  - shapely
  - notebook
  - scikit-learn